// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRjPh63olVSRva3P67DpglAtf1rZb9yq0',
    appId: '1:193529579342:web:4ce0a1a6391dd71a81001f',
    messagingSenderId: '193529579342',
    projectId: 'fir-authapp-af8dc',
    authDomain: 'fir-authapp-af8dc.firebaseapp.com',
    storageBucket: 'fir-authapp-af8dc.firebasestorage.app',
    measurementId: 'G-C4414JZPFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZaCoIQSsZJYXvEcJcJ6BiG-abnJQWjQ0',
    appId: '1:193529579342:android:012abed2aee4cd7381001f',
    messagingSenderId: '193529579342',
    projectId: 'fir-authapp-af8dc',
    storageBucket: 'fir-authapp-af8dc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBugK_fQmvrJJzCUU6rPndALVQWwjBVkBI',
    appId: '1:193529579342:ios:197ec0bb73c7f8bf81001f',
    messagingSenderId: '193529579342',
    projectId: 'fir-authapp-af8dc',
    storageBucket: 'fir-authapp-af8dc.firebasestorage.app',
    androidClientId:
        '193529579342-vfi0ff4kmn7lkisj0i1kva9tjh4cn6bd.apps.googleusercontent.com',
    iosClientId:
        '193529579342-1rd08sodjrt4bhkdbbea7tr8gftf5pkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthenticationApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBugK_fQmvrJJzCUU6rPndALVQWwjBVkBI',
    appId: '1:193529579342:ios:197ec0bb73c7f8bf81001f',
    messagingSenderId: '193529579342',
    projectId: 'fir-authapp-af8dc',
    storageBucket: 'fir-authapp-af8dc.firebasestorage.app',
    androidClientId:
        '193529579342-vfi0ff4kmn7lkisj0i1kva9tjh4cn6bd.apps.googleusercontent.com',
    iosClientId:
        '193529579342-1rd08sodjrt4bhkdbbea7tr8gftf5pkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthenticationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRjPh63olVSRva3P67DpglAtf1rZb9yq0',
    appId: '1:193529579342:web:d84da3562b0405c881001f',
    messagingSenderId: '193529579342',
    projectId: 'fir-authapp-af8dc',
    authDomain: 'fir-authapp-af8dc.firebaseapp.com',
    storageBucket: 'fir-authapp-af8dc.firebasestorage.app',
    measurementId: 'G-DMTSLTWG3S',
  );
}
